let cardDeck = [
    {
        id: 1,
        name: 'Achilles',
        src: './img/achilles.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 2,
        name: 'Anubis',
        src: './img/anubis.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 3,
        name: 'Beawulf',
        src: './img/beawulf.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 4,
        name: 'Cúchulainn',
        src: './img/cuchulainn.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 5,
        name: 'Gilgamesh',
        src: './img/gilgamesh.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 6,
        name: 'Hanuman',
        src: './img/hanuman.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 7,
        name: 'Hercules',
        src: './img/hercules.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 8,
        name: 'King Arthur',
        src: './img/arthur.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 9,
        name: 'Krishna',
        src: './img/krishna.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 10,
        name: 'Minothaur',
        src: './img/minothaur.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 11,
        name: 'Perseus',
        src: './img/perseus.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 12,
        name: 'Rostman',
        src: './img/rostman.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 13,
        name: 'Thor',
        src: './img/thor.png',
        face__src: './img/faceSide.png',
    },
    {
        id: 14,
        name: 'Sun Wukong',
        src: './img/wukong.png',
        face__src: './img/faceSide.png',
    },
]